version: '3'
services:
  api:
    container_name: loopminterjs-api
    build: ./api
    image: loopminterjs/api
  image:
    container_name: loopminterjs-image-generator
    build: ./image_generator
    image: loopminterjs/image_generator
  dashboard:
    container_name: loopminterjs-dashboard
    build: ./dashboard
    image: loopminterjs/dashboard
  proxy:
    container_name: loopminterjs-proxy 
    build: ./proxy
    image: loopminterjs/proxy
    env_file: ./proxy/.env.docker
