version: '3'
services:
  proxy:
    ports:
      - '8080:8080'
    command: npm run dev
  api:
    ports:
      - '8001:8001'
    command: npm run dev
  image:
    ports:
      - '8002:8002'
    command: npm run dev
  dashboard:
    ports:
      - '8000:8000'